"use strict";
(function(){
 const store=window.ATLAS_STORE,ui=window.ATLAS_UI,data=store.data;
 const SCREENS=[
  {id:"overview",label:"Genel Bakış"},{id:"inbox",label:"Gelen Kutusu"},{id:"appointments",label:"Randevular"},{id:"customers",label:"Müşteriler / Leadler"},{id:"campaigns",label:"Kampanyalar"},{id:"automations",label:"Otomasyonlar"},{id:"services",label:"Hizmetler / Fiyatlar"},{id:"ai",label:"AI Asistan Ayarları"},{id:"widget",label:"Tasarım / Widget"},{id:"plugins",label:"Eklentiler"},{id:"analytics",label:"Analitik"},{id:"team",label:"Ekip / Yetkiler"},{id:"settings",label:"Ayarlar"}
 ];
 const main=document.getElementById("main"),nav=document.getElementById("nav");
 function header(title,sub){const f=document.createDocumentFragment();f.appendChild(ui.el("h1",{text:title}));f.appendChild(ui.el("p",{class:"sub",text:sub}));return f}
 function cardTable(title,headers,rows){return ui.el("div",{class:"card"},[ui.el("h2",{text:title}),ui.table(headers,rows)])}
 function screenOverview(){const f=header("Genel Bakış",data.business.name+" — "+data.business.city+" (tüm veriler demo)");const g=ui.el("div",{class:"grid"});data.kpis.forEach(k=>{const c=ui.el("div",{class:"card"});c.appendChild(ui.el("div",{class:"kpi-label",text:k.label}));c.appendChild(ui.el("div",{class:"kpi-value",text:k.value}));c.appendChild(ui.el("span",{class:"tag warn",text:"demo"}));g.appendChild(c)});f.appendChild(g);f.appendChild(ui.el("div",{class:"notice",text:"Bugünkü özet: 12 randevu, 2 iptal, 1 yoklama (demo veri)."}));return f}
 function screenInbox(){const f=header("Gelen Kutusu","Mock kanallar: WhatsApp, Instagram DM (canlı bağlantı yok)");const rows=data.inbox.map(m=>[m.channel,m.from,m.text,ui.el("span",{class:m.risk==="yüksek"?"tag danger":"tag ok",text:m.risk})]);f.appendChild(cardTable("Mesajlar (mock)",["Kanal","Gönderen","Mesaj","Risk"],rows));f.appendChild(ui.handoverBox());return f}
 function screenAppointments(){const f=header("Randevular","Bugünün mock programı");f.appendChild(cardTable("Bugün (demo)",["Saat","Müşteri","Hizmet","Durum"],data.appointments.map(a=>[a.time,a.customer,a.service,a.status])));const row=ui.el("div",{class:"form-row"});const a=ui.el("button",{class:"btn",text:"a1 onayla (mock)"});a.addEventListener("click",()=>store.actions.confirmAppointment("a1"));const b=ui.el("button",{class:"btn danger",text:"a2 iptal (mock)"});b.addEventListener("click",()=>store.actions.cancelAppointment("a2"));row.appendChild(a);row.appendChild(b);f.appendChild(row);return f}
 function screenCustomers(){const f=header("Müşteriler / Leadler","Demo kayıtlar; telefonlar sahte ve maskeli");f.appendChild(cardTable("Leadler (demo)",["Müşteri","Telefon (sahte)","Lead durumu","Kaynak"],data.customers.map(c=>[c.name,c.phone,c.leadStatus,c.source])));return f}
 function screenCampaigns(){const f=header("Kampanyalar","Taslak ve hedefleme ön izleme");f.appendChild(ui.el("div",{class:"notice",text:"Kampanyalar bu prototipte gönderilmez; yalnızca taslak ve hedefleme ön izlemesidir."}));f.appendChild(cardTable("Kampanyalar (demo)",["Kampanya","Hedefleme","Durum"],store.get().draftCampaigns.map(c=>[c.name,c.audience,c.state])));const input=ui.el("input",{type:"text",placeholder:"Yeni kampanya adı (mock)"}),b=ui.el("button",{class:"btn",text:"Taslak kaydet (mock)"});b.addEventListener("click",()=>{store.actions.saveDraftCampaign(input.value);input.value=""});const row=ui.el("div",{class:"form-row"});row.appendChild(input);row.appendChild(b);f.appendChild(row);return f}
 function screenAutomations(){const f=header("Otomasyonlar","Mock tetikleyiciler");const rows=data.automations.map(a=>{const b=ui.el("button",{class:"btn ghost",text:"Aç/Kapat (mock)"});b.addEventListener("click",()=>store.actions.toggleAutomation(a.id));return[a.name,a.trigger,a.active?"açık":"kapalı",b]});f.appendChild(cardTable("Otomasyonlar (demo)",["Otomasyon","Tetikleyici","Durum","İşlem"],rows));return f}
 function screenServices(){const f=header("Hizmetler / Fiyatlar","Örnek hizmet listesi (fiyatlar demo)");f.appendChild(cardTable("Hizmetler (demo)",["Hizmet","Fiyat (demo)"],data.services.map(s=>[s.name,s.price])));return f}
 function screenAI(){const f=header("AI Asistan Ayarları","Mock yapılandırma"),a=data.aiSettings;f.appendChild(cardTable("Ayarlar (demo)",["Ayar","Değer"],[["Ton",a.tone],["Otomatik yanıt",a.autoReply],["Devralma anahtar kelimeleri",a.handoverKeywords.join(", ")]]));f.appendChild(ui.el("div",{class:"notice info",text:"Sağlık, şikâyet veya belirsiz sorularda insan devralma akışı etkindir (mock)."}));return f}
 function screenWidget(){const f=header("Tasarım / Widget","Ön izleme");f.appendChild(ui.el("div",{class:"notice",text:"Yakında — yayın öncesinde domain, güvenlik ve sağlayıcı kurulumu gerekir."}));f.appendChild(cardTable("Widget (demo)",["Ayar","Değer"],[["Tema",data.widget.theme],["Konum",data.widget.position]]));return f}
 function screenPlugins(){const f=header("Eklentiler","Mock bağlayıcılar; hiçbiri kurulmaz");const rows=data.plugins.map(p=>{const b=ui.el("button",{class:"btn ghost",text:"Durumu değiştir (mock)"});b.addEventListener("click",()=>store.actions.togglePlugin(p.id));return[p.name,p.installed?"kurulu":"kurulu değil",b]});f.appendChild(cardTable("Eklentiler (demo)",["Eklenti","Durum","İşlem"],rows));return f}
 function screenAnalytics(){const f=header("Analitik","Demo metrikler");f.appendChild(ui.el("div",{class:"notice",text:"Demo tahmin — kesin gelir veya tahsilat verisi değildir."}));const g=ui.el("div",{class:"grid"});[["Gelir (ay)",data.analytics.revenueMonth],["Dönüşüm",data.analytics.conversion],["En iyi hizmet",data.analytics.bestService]].forEach(x=>{const c=ui.el("div",{class:"card"});c.appendChild(ui.el("div",{class:"kpi-label",text:x[0]}));c.appendChild(ui.el("div",{class:"kpi-value",text:x[1]}));c.appendChild(ui.el("span",{class:"tag warn",text:"demo tahmin"}));g.appendChild(c)});f.appendChild(g);return f}
 function screenTeam(){const f=header("Ekip / Yetkiler","Roller prototipte adlandırılmıştır; gerçek yetkilendirme iddiası yoktur");f.appendChild(cardTable("Ekip (demo)",["Kullanıcı","Rol","Yetki (mock)"],data.team.map(u=>[u.name,u.role,u.perm])));return f}
 function screenSettings(){const f=header("Ayarlar","İşletme ayarları (mock)");f.appendChild(cardTable("Ayarlar (demo)",["Ayar","Değer"],[["Dil",data.settings.language],["Saat dilimi",data.settings.timezone],["Veri saklama",data.settings.dataRetention]]));return f}
 const RENDER={overview:screenOverview,inbox:screenInbox,appointments:screenAppointments,customers:screenCustomers,campaigns:screenCampaigns,automations:screenAutomations,services:screenServices,ai:screenAI,widget:screenWidget,plugins:screenPlugins,analytics:screenAnalytics,team:screenTeam,settings:screenSettings};
 function render(){const s=store.get(),id=s.screen||"overview";ui.clear(nav);SCREENS.forEach(x=>{const a=ui.el("a",{href:"#"+x.id,text:x.label});if(x.id===id)a.className="active";nav.appendChild(a)});ui.clear(main);main.appendChild((RENDER[id]||screenOverview)())}
 store.subscribe(s=>{if(s.lastToast)ui.toast(s.lastToast.msg);render()});
 window.addEventListener("hashchange",()=>{const id=(location.hash||"#overview").slice(1);if(SCREENS.some(x=>x.id===id))store.set({screen:id})});
 const initial=(location.hash||"#overview").slice(1);store.set({screen:SCREENS.some(x=>x.id===initial)?initial:"overview"});
})();
