"use strict";
(function(){
 const store=window.ATLAS_STORE,ui=window.ATLAS_UI,data=store.data;
 const SCREENS=[
  {id:"overview",label:"Genel Bakış"},{id:"inbox",label:"Gelen Kutusu"},{id:"appointments",label:"Randevular"},{id:"customers",label:"Müşteriler / Leadler"},{id:"campaigns",label:"Kampanyalar"},{id:"automations",label:"Otomasyonlar"},{id:"services",label:"Hizmetler / Fiyatlar"},{id:"ai",label:"AI Asistan Ayarları"},{id:"widget",label:"Tasarım / Widget"},{id:"plugins",label:"Eklentiler"},{id:"analytics",label:"Analitik"},{id:"team",label:"Ekip / Yetkiler"},{id:"settings",label:"Ayarlar"}
 ];
 const main=document.getElementById("main"),nav=document.getElementById("nav");
 function normScreen(id){return id==="ai-settings"?"ai":id}
 function header(title,sub){const f=document.createDocumentFragment();f.appendChild(ui.el("h1",{text:title}));f.appendChild(ui.el("p",{class:"sub",text:sub}));return f}
 function cardTable(title,headers,rows){return ui.el("div",{class:"card"},[ui.el("h2",{text:title}),ui.table(headers,rows)])}
 function screenOverview(){const f=header("Genel Bakış",data.business.name+" — "+data.business.city);if(window.ATLAS_APPTS&&window.ATLAS_APPTS.mountOverview){window.ATLAS_APPTS.mountOverview(f)}else{const g=ui.el("div",{class:"grid"});data.kpis.forEach(k=>{const c=ui.el("div",{class:"card"});c.appendChild(ui.el("div",{class:"kpi-label",text:k.label}));c.appendChild(ui.el("div",{class:"kpi-value",text:k.value}));c.appendChild(ui.el("span",{class:"tag warn",text:"demo"}));g.appendChild(c)});f.appendChild(g);f.appendChild(ui.el("div",{class:"notice",text:"Bugünkü özet: 12 randevu, 2 iptal, 1 yoklama (demo veri)."}))}return f}
 function screenInbox(){const f=header("Gelen Kutusu","Canlı sohbet — müşteri listesi, mesaj akışı ve gönderim (Supabase Realtime)");if(window.ATLAS_INBOX){window.ATLAS_INBOX.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Gelen kutusu yükleniyor…"}))}return f}
 function screenAppointments(){const f=header("Randevular","Günlük takvim — Supabase appointments tablosundan (canlı)");if(window.ATLAS_APPTS){window.ATLAS_APPTS.mountRandevular(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Randevular yükleniyor…"}))}return f}
 function screenCustomers(){const f=header("Müşteriler / Leadler","Canlı — Supabase customers + lead skorlama (satışa hazır)");if(window.ATLAS_CUSTOMERS&&window.ATLAS_CUSTOMERS.mount){window.ATLAS_CUSTOMERS.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Müşteriler yükleniyor…"}))}return f}
 function screenCampaigns(){const f=header("Kampanyalar","Taslak + canlı hedefleme önizleme — Supabase");if(window.ATLAS_CAMPAIGNS&&window.ATLAS_CAMPAIGNS.mount){window.ATLAS_CAMPAIGNS.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Kampanyalar yükleniyor…"}))}return f}
 function screenAutomations(){const f=header("Otomasyonlar","AI cevapları, çalışma saatleri ve fallback — Supabase assistant_settings (canlı)");if(window.ATLAS_AUTOMATIONS&&window.ATLAS_AUTOMATIONS.mount){window.ATLAS_AUTOMATIONS.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Otomasyon ayarları yükleniyor…"}))}return f}
 function screenServices(){const f=header("Hizmetler / Fiyatlar","Canlı liste — Supabase");if(window.ATLAS_SERVICES&&window.ATLAS_SERVICES.mount){window.ATLAS_SERVICES.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Hizmetler yükleniyor…"}))}return f}
 function screenAI(){const f=header("AI Asistan Ayarları","Prompt ve model ayarları — Supabase assistant_settings tablosundan (canlı)");if(window.ATLAS_AI&&window.ATLAS_AI.mount){window.ATLAS_AI.mount(f)}else{const a=data.aiSettings;f.appendChild(cardTable("Ayarlar (demo)",["Ayar","Değer"],[["Ton",a.tone],["Otomatik yanıt",a.autoReply],["Devralma anahtar kelimeleri",a.handoverKeywords.join(", ")]]));f.appendChild(ui.el("div",{class:"notice info",text:"Sağlık, şikâyet veya belirsiz sorularda insan devralma akışı etkindir (mock)."}))}return f}
 function screenWidget(){const f=header("Tasarım / Widget","Ön izleme");f.appendChild(ui.el("div",{class:"notice",text:"Yakında — yayın öncesinde domain, güvenlik ve sağlayıcı kurulumu gerekir."}));f.appendChild(cardTable("Widget (demo)",["Ayar","Değer"],[["Tema",data.widget.theme],["Konum",data.widget.position]]));return f}
 function screenPlugins(){const f=header("Eklentiler","Mock bağlayıcılar; hiçbiri kurulmaz");const rows=data.plugins.map(p=>{const b=ui.el("button",{class:"btn ghost",text:"Durumu değiştir (mock)"});b.addEventListener("click",()=>store.actions.togglePlugin(p.id));return[p.name,p.installed?"kurulu":"kurulu değil",b]});f.appendChild(cardTable("Eklentiler (demo)",["Eklenti","Durum","İşlem"],rows));return f}
 function screenAnalytics(){const f=header("Analitik","Son 7 gün — Supabase messages tablosundan (canlı)");if(window.ATLAS_ANALYTICS&&window.ATLAS_ANALYTICS.mount){window.ATLAS_ANALYTICS.mount(f)}else{f.appendChild(ui.el("div",{class:"card",text:"Analitik yükleniyor…"}))}return f}
 function screenTeam(){const f=header("Ekip / Yetkiler","Roller prototipte adlandırılmıştır; gerçek yetkilendirme iddiası yoktur");f.appendChild(cardTable("Ekip (demo)",["Kullanıcı","Rol","Yetki (mock)"],data.team.map(u=>[u.name,u.role,u.perm])));return f}
 function screenSettings(){const f=header("Ayarlar","İşletme ayarları (mock)");f.appendChild(cardTable("Ayarlar (demo)",["Ayar","Değer"],[["Dil",data.settings.language],["Saat dilimi",data.settings.timezone],["Veri saklama",data.settings.dataRetention]]));return f}
 const RENDER={overview:screenOverview,inbox:screenInbox,appointments:screenAppointments,customers:screenCustomers,campaigns:screenCampaigns,automations:screenAutomations,services:screenServices,ai:screenAI,widget:screenWidget,plugins:screenPlugins,analytics:screenAnalytics,team:screenTeam,settings:screenSettings};
 function render(){const s=store.get(),id=normScreen(s.screen||"overview");ui.clear(nav);SCREENS.forEach(x=>{const a=ui.el("a",{href:"#"+x.id,text:x.label});if(x.id===id)a.className="active";nav.appendChild(a)});ui.clear(main);main.appendChild((RENDER[id]||screenOverview)())}
 store.subscribe(s=>{if(s.lastToast)ui.toast(s.lastToast.msg);render()});
 window.addEventListener("hashchange",()=>{const id=normScreen((location.hash||"#overview").slice(1));if(SCREENS.some(x=>x.id===id))store.set({screen:id})});
 window.atlasBoot=function(){const initial=normScreen((location.hash||"#overview").slice(1));store.set({screen:SCREENS.some(x=>x.id===initial)?initial:"overview"})};
})();
