"use strict";
/* FAZ 13 — Genel Bakış + Randevular: Satışa hazır canlı KPI'lar */
(function(){
 var ui = window.ATLAS_UI;
 var STATUS_LABEL = { pending:"beklemede", scheduled:"onaylı", cancelled:"iptal", no_show:"yoklama", completed:"tamamlandı" };
 function statusLabel(s){ return STATUS_LABEL[s] || String(s || "-"); }
 function statusTag(s){ var cls = s === "cancelled"? "tag danger" : (s === "no_show"? "tag warn" : "tag ok"); return ui.el("span", { class: cls, text: statusLabel(s) }); }
 function dayRange(d){ var start=new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0); var end=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1,0,0,0,0); return {start:start.toISOString(), end:end.toISOString()}; }
 function fmtTime(iso){ try{ return new Date(iso).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});}catch(e){return"";} }
 function fetchOrgId(){ var sb=window.ATLAS_SUPABASE, u=window.atlasUser; if(!sb||!u) return Promise.reject(new Error("Oturum yok")); return sb.from("users").select("organization_id").eq("id",u.id).limit(1).maybeSingle().then(function(r){ if(r.error) throw new Error(r.error.message); if(!r.data||!r.data.organization_id) throw new Error("Org yok"); return r.data.organization_id; }); }
 function statsAppointments(sb){ var r=dayRange(new Date()); return Promise.all([ sb.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",r.start).lt("starts_at",r.end).neq("status","cancelled"), sb.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",r.start).lt("starts_at",r.end).eq("status","cancelled"), sb.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",r.start).lt("starts_at",r.end).eq("status","no_show"), sb.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",new Date().toISOString()).lt("starts_at", new Date(Date.now()+24*3600*1000).toISOString()) ]).then(function(rs){ return {today:(rs[0]&&rs[0].count)||0, cancelled:(rs[1]&&rs[1].count)||0, noShow:(rs[2]&&rs[2].count)||0, tomorrow:(rs[3]&&rs[3].count)||0}; }); }
 function statsMessages(sb, orgId){ var since=new Date(Date.now()-7*24*3600*1000).toISOString(); var todayStart=dayRange(new Date()).start; return Promise.all([ sb.from("messages").select("id",{count:"exact",head:true}).eq("organization_id",orgId).gte("created_at", todayStart), sb.from("messages").select("id,customer_id,sender_type").eq("organization_id",orgId).gte("created_at", since).limit(1000), sb.from("services").select("id",{count:"exact",head:true}).eq("organization_id",orgId).eq("is_active",true) ]).then(function(rs){ var todayMsg=(rs[0]&&rs[0].count)||0; var rows=rs[1]&&rs[1].data? rs[1].data: []; var activeCustomers = new Set(rows.map(function(r){return r.customer_id;})).size; var ai = rows.filter(function(r){return r.sender_type==="ai";}).length; var rate = rows.length? Math.round(ai/rows.length*100):0; var svcCount=(rs[2]&&rs[2].count)||0; return {todayMsg:todayMsg, activeCustomers:activeCustomers, aiRate:rate, svcCount:svcCount}; }); }
 function kpiCard(label, value, tagText, tagClass){ var c=ui.el("div",{class:"card"}); c.appendChild(ui.el("div",{class:"kpi-label",text:label})); c.appendChild(ui.el("div",{class:"kpi-value",text:String(value)})); if(tagText) c.appendChild(ui.el("span",{class:tagClass||"tag ok",text:tagText})); return c; }
 function mountOverview(f){
  var hero=ui.el("div",{class:"card"}); hero.appendChild(ui.el("h2",{text:"Genel Bakış — Canlı Operasyon (Satışa hazır)"})); hero.appendChild(ui.el("p",{text:"Bugün ne oldu? Tüm veriler canlı. Demo'da buradan başlayın.", class:"muted"})); f.appendChild(hero);
  var g1=ui.el("div",{class:"grid"}); var cToday=kpiCard("Bugünkü randevu","…"); var cCancel=kpiCard("İptal","…"); var cNoShow=kpiCard("Yoklama","…"); var cTomorrow=kpiCard("Yarın","…"); [cToday,cCancel,cNoShow,cTomorrow].forEach(function(c){g1.appendChild(c);}); f.appendChild(g1);
  var g2=ui.el("div",{class:"grid kpi-grid"}); var cMsg=kpiCard("Bugünkü mesaj","…"); var cActive=kpiCard("Aktif müşteri (7g)","…"); var cAi=kpiCard("AI çözme","…"); var cSvc=kpiCard("Aktif hizmet","…"); [cMsg,cActive,cAi,cSvc].forEach(function(c){g2.appendChild(c);}); f.appendChild(g2);
  var notice=ui.el("div",{class:"notice",text:"İstatistikler yükleniyor…"}); f.appendChild(notice);
  var sb=window.ATLAS_SUPABASE; if(!sb){ notice.textContent="Supabase yok"; return; }
  fetchOrgId().then(function(orgId){ return Promise.all([statsAppointments(sb), statsMessages(sb, orgId)]).then(function(all){ var s=all[0], m=all[1]; cToday.querySelector(".kpi-value").textContent=String(s.today); cCancel.querySelector(".kpi-value").textContent=String(s.cancelled); cNoShow.querySelector(".kpi-value").textContent=String(s.noShow); cTomorrow.querySelector(".kpi-value").textContent=String(s.tomorrow); cMsg.querySelector(".kpi-value").textContent=String(m.todayMsg); cActive.querySelector(".kpi-value").textContent=String(m.activeCustomers); cAi.querySelector(".kpi-value").textContent="%"+m.aiRate; cSvc.querySelector(".kpi-value").textContent=String(m.svcCount); [cToday,cCancel,cNoShow,cTomorrow,cMsg,cActive,cAi,cSvc].forEach(function(c){ if(!c.querySelector(".tag")){ c.appendChild(ui.el("span",{class:"tag ok",text:"canlı"})); }}); notice.textContent="Bugün: "+s.today+" randevu, "+s.cancelled+" iptal, "+s.noShow+" yoklama — "+m.todayMsg+" mesaj, "+m.activeCustomers+" aktif müşteri, AI %"+m.aiRate+" çözüyor. "+m.svcCount+" aktif hizmet."; notice.className="notice info"; var pitch=ui.el("div",{class:"card"}); pitch.appendChild(ui.el("h3",{text:"Satış pitch — Genel Bakış'ta söyle"})); pitch.appendChild(ui.el("p",{text:"'Bugün "+m.todayMsg+" müşteri yazdı, AI %"+m.aiRate+" ünü otomatik cevapladı. "+s.today+" randevunuz var, yarın "+s.tomorrow+" — hepsi canlı. Hizmetleriniz ("+m.svcCount+") AI'da anında güncel.'"})); f.appendChild(pitch); }); }).catch(function(e){ notice.textContent="Yüklenemedi: "+e.message; });
 }
 var STYLE_ID="appt-modal-style";
 function ensureStyles(){ if(document.getElementById(STYLE_ID)) return; var s=document.createElement("style"); s.id=STYLE_ID; s.textContent=".appt-row-actions{display:flex;gap:.35rem;flex-wrap:wrap}.appt-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:50;display:flex;align-items:center;justify-content:center;padding:1rem}.appt-modal{background:var(--bg,#fff);color:inherit;border-radius:12px;max-width:520px;width:100%;padding:1.25rem;box-shadow:0 12px 40px rgba(0,0,0,.25)}.appt-modal h2{margin:0 0.75rem}.appt-modal label{display:block;margin:.5rem 0.25rem;font-weight:600}.appt-modal input,.appt-modal select,.appt-modal textarea{width:100%;box-sizing:border-box;padding:.4rem;border-radius:8px;border:1px solid #ccc}.appt-modal textarea{min-height:70px}.appt-modal.appt-err{color:#b00;margin-top:.5rem}.appt-nav{display:flex;gap:.5rem;align-items:center;margin-bottom:.75rem}"; document.head.appendChild(s); }
 function closeModal(){ var m=document.getElementById("appt-modal"); if(m) m.remove(); }
 document.addEventListener("keydown", function(ev){ if(ev.key==="Escape") closeModal(); });
 function actionBtn(label, cls, fn){ var b=ui.el("button",{class:cls||"btn ghost",text:label}); b.addEventListener("click", fn); return b; }
 function setStatus(id, status, onDone){ var sb=window.ATLAS_SUPABASE; sb.from("appointments").update({status:status}).eq("id",id).then(function(res){ if(res.error) ui.toast("Güncellenemedi: "+res.error.message); else { ui.toast("Durum: "+status); if(onDone) onDone(); } }); }
 function mountRandevular(f){
  ensureStyles(); var wrap=ui.el("div"); f.appendChild(wrap); var sb=window.ATLAS_SUPABASE; if(!sb){ wrap.appendChild(ui.el("p",{text:"Supabase bekleniyor…"})); return; }
  var nav=ui.el("div",{class:"appt-nav"}); var dateInput=ui.el("input",{type:"date"}); dateInput.valueAsDate=new Date(); var loadBtn=ui.el("button",{class:"btn",text:"Yükle"}); nav.appendChild(dateInput); nav.appendChild(loadBtn); wrap.appendChild(nav);
  var list=ui.el("div"); wrap.appendChild(list);
  function load(){ ui.clear(list); list.appendChild(ui.el("p",{text:"Yükleniyor…"})); var d=dateInput.valueAsDate||new Date(); var start=new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0).toISOString(); var end=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1,0,0,0,0).toISOString(); sb.from("appointments").select("id,starts_at,status,customer_id,customers(name)").gte("starts_at",start).lt("starts_at",end).order("starts_at").then(function(res){ ui.clear(list); if(res.error){ list.appendChild(ui.el("p",{text:"Hata: "+res.error.message})); return; } var rows=res.data||[]; if(!rows.length){ list.appendChild(ui.el("div",{class:"card",text:"Bu tarihte randevu yok."})); return; } var t=ui.el("table"); var thead=ui.el("thead"); var htr=ui.el("tr"); ["Saat","Müşteri","Durum","İşlem"].forEach(function(h){ htr.appendChild(ui.el("th",{text:h})); }); thead.appendChild(htr); t.appendChild(thead); var tbody=ui.el("tbody"); rows.forEach(function(ap){ var tr=ui.el("tr"); try{ tr.appendChild(ui.el("td",{text:new Date(ap.starts_at).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})})); }catch(e){ tr.appendChild(ui.el("td",{text:"—"})); } tr.appendChild(ui.el("td",{text:(ap.customers&&ap.customers.name)||ap.customer_id||"—"})); var tdS=ui.el("td"); tdS.appendChild(statusTag(ap.status)); tr.appendChild(tdS); var tdA=ui.el("td"); tdA.appendChild(actionBtn("Onayla","btn ghost",function(){ setStatus(ap.id,"scheduled",load); })); tdA.appendChild(actionBtn("İptal","btn danger",function(){ setStatus(ap.id,"cancelled",load); })); tr.appendChild(tdA); tbody.appendChild(tr); }); t.appendChild(tbody); list.appendChild(t); }); }
  loadBtn.addEventListener("click", load); load();
 }
 window.ATLAS_APPTS={mountOverview:mountOverview, mountRandevular:mountRandevular};
})();
